name : Multi Triggers

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  system-info:
    runs-on : ubuntu-latest

    
    steps:

     # Install neofetch (required)
      - name: Install neofetch
        run: sudo apt-get update && sudo apt-get install -y neofetch
        
      - name : running neofetch
        run: 
          neofetch
      - name : running uname
        run : 
          uname -a 